on:
  release:
    types: [published]
permissions:
  contents:
    write

jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python: [ "3.10", "3.11", "3.12", "3.13", "3.14"]
        
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      
      - name: Checkout repository and submodules
        uses: actions/checkout@v5
        with:
          submodules: recursive
        
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          
      - name: Install and build C++ dependencies
        run: ./scripts/install.bat
        
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest geopandas
        
      - name: Build package
        run: ./scripts/build.bat
        
      - name: Run pytests
        run: pytest

  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.10", "3.11", "3.12", "3.13", "3.14"]
        
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      
      - name: Checkout repository and submodules
        uses: actions/checkout@v5
        with:
          submodules: recursive
        
      - name: Install and build C++ dependencies
        run: bash scripts/install.sh
        
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest geopandas
        
      - name: Build package
        run: bash scripts/build.sh
        
      - name: Run pytests
        run: pytest

  build-windows:
    needs: 
      - test-windows
      - test-linux
    runs-on: windows-latest
    strategy:
      matrix:
        python: [ "3.10", "3.11", "3.12", "3.13", "3.14"]
        
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          
      - name: Checkout repository and submodules
        uses: actions/checkout@v5
        with:
          submodules: recursive
 
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          
      - name: Install and build C++ dependencies
        run: ./scripts/install.bat
        
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
        
      - name: Build wheel
        run: ./scripts/build_dist.bat

      - name: Save wheel artifact
        uses: actions/upload-artifact@v5
        with:
          name: windows-python${{ matrix.python }}-wheel
          path: dist/*.whl

  build-linux:
    needs: 
      - test-windows
      - test-linux
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      
      - name: Checkout repository and submodules
        uses: actions/checkout@v5
        with:
          submodules: recursive
          
      - name: Install and build C++ dependencies
        run: bash scripts/install.sh
        
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build auditwheel cibuildwheel
        
      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-* cp314-*"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux_2_28"
          CIBW_SKIP: "*-musllinux_*"
          CIBW_ENVIRONMENT: PKG_CONFIG_PATH="/project/sgspy/extern/vcpkg/installed/x64-linux/lib/pkgconfig"
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: "auditwheel repair -w {dest_dir} {wheel} --exclude libmkl_core.so.2 --exclude libmkl_tbb_thread.so.2 --exclude libmkl_intel_ilp64.so.2 --exclude libonedal_parameters.so.3 --exclude libonedal_core.so.3 --exclude libonedal_thread.so.3 --exclude libonedal.so.3"
          
      - name: Save wheel artifact
        uses: actions/upload-artifact@v5
        with:
          name: linux-wheels
          path: dist/*.whl

  pypi-publish:
    needs: 
      - build-windows 
      - build-linux
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
  
    steps:
      - name: Retrive wheel files
        uses: actions/download-artifact@v5
        with:
          path: dist/
          merge-multiple: true

      - name: View Wheel Files
        run: ls -r dist
  
      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
