on:
  push:
    branches:
      - test-manylinux_2_35
permissions:
  contents:
    write

jobs:
  build-linux:
    runs-on: ${{ matrix.os.version }}
    strategy:
      matrix:
        python: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]
        os: [
          { version: ubuntu-latest, platform: manylinux_2_39_x86_64 },
          { version: ubuntu-22.04, platform: manylinux_2_35_x86_64 }
        ]

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          
      - name: Checkout repository and submodules
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup C/C++ Compiler
        id: setup-compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: gcc-latest

      - name: Check gcc version
        run: |
          gcc --version
          g++ --version
          
      - name: Install and build C++ dependencies
        run: bash scripts/install.sh
        
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build auditwheel
        
      - name: Build wheel
        run: bash scripts/build_dist.sh

      - name: Repair wheel ubuntu-latest
        run: |
         auditwheel repair dist/*.whl -w dist --plat ${{ matrix.os.platform }} --exclude libmkl_core.so.2 --exclude libmkl_tbb_thread.so.2 --exclude libmkl_intel_ilp64.so.2 --exclude libonedal_parameters.so.3 --exclude libonedal_core.so.3 --exclude libonedal_thread.so.3 --exclude libonedal.so.3
         rm dist/*linux_x86_64.whl

      - name: Save wheel artifact
        uses: actions/upload-artifact@v5
        with:
          name: linux-python${{ matrix.python }}-wheel
          path: dist/*.whl

