on:
  push:
    branches:
      - test-manylinux_2_35
permissions:
  contents:
    write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      
      - name: Checkout repository and submodules
        uses: actions/checkout@v5
        with:
          submodules: recursive
          
      - name: Install and build C++ dependencies
        run: bash scripts/install.sh
        
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build auditwheel cibuildwheel
        
      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-* cp314-*"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux_2_28"
          CIBW_ENVIRONMENT: PKG_CONFIG_PATH="/project/sgspy/extern/vcpkg/installed/x64-linux/lib/pkgconfig"
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: "auditwheel repair {dest_dir} {wheel} --exclude libmkl_core.so.2 --exclude libmkl_tbb_thread.so.2 --exclude libmkl_intel_ilp64.so.2 --exclude libonedal_parameters.so.3 --exclude libonedal_core.so.3 --exclude libonedal_thread.so.3 --exclude libonedal.so.3"
          
      - name: Save wheel artifact
        uses: actions/upload-artifact@v5
        with:
          name: linux-python${{ matrix.python }}-wheel
          path: dist/*.whl
